### ISSUE TITLE
Is this plugin supported?

### ISSUE THREAD

**Issue by mgiammarco** [opennms-forge/timeseries-integration-influxdb#7]
Hello,
I am trying to do "mvn clean install".
I immediately see that opennms.api.version must be changed to 0.5.1 from 0.5.1-snapshot.
Then I have another bigger problem (I opened another issue for this).
Your last commit is of several month ago. Nobody raised an issue.
Is this plugin considered supported/production level or is it just an "integration demo" that shows what can you do with opennms?
Thanks,
Mario

**Comment by indigo423** [comment]
I've set the OIA plugin to version 0.5.1. Can you verify if this solves your building error? If this fixes the problem for you I'll go ahead and merge the PR.

**Comment by indigo423** [comment]
Regarding to your question is it supported. We have it working and and it also got some performance improvements. I would say it is in an early stage of development but functioning. With my OpenNMS employee hat on, we don't provide commercial support in critical environments for this plugin at this point in time. We need definitely more feedback from people like you to make it more mature and get wider adoption. Thank you for the time digging into issues and giving feedback.

**Comment by mgiammarco** [comment]
It is enough for me that someone uses it in addition to me. I will for now put in my test environment.
