### ISSUE TITLE
Missing JAXBException

### ISSUE THREAD

**Issue by mgiammarco** [opennms-forge/timeseries-integration-influxdb#8]
When I do mvn clean install in the KAR assembly phase I get:

[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.1.5:features-generate-descriptor (default-features-generate-descriptor) on project org.opennms.plugins.timeseries.influxdb.assembly.kar: Execution default-features-generate-descriptor of goal org.apache.karaf.tooling:karaf-maven-plugin:4.1.5:features-generate-descriptor failed: A required class was missing while executing org.apache.karaf.tooling:karaf-maven-plugin:4.1.5:features-generate-descriptor: javax/xml/bind/JAXBException

Is it possible that it is due to the fact I am using Java11 openjdk?

**Comment by mgiammarco** [comment]
Solved by bumping karaf version to 4.3.0

**Comment by indigo423** [comment]
@mgiammarco thanks for digging into this. OpenNMS itself requires to be compiled with Java 1.8. It can run on JDK 11. I'm not sure if we have side effects when you bump the Karaf dependency and compile it with Java 11. @patrick-schweizer maybe you can give some hints here. If it is not a problem we should bump Karaf to 4.3.0 to be able to compile with Java 11.

**Comment by mgiammarco** [comment]
Regarding Java11 I tried to do a "standard" install. I downloaded debian stable, added opennms repo and I do "apt install..."
I let apt-get choose the java version.

**Comment by mgiammarco** [comment]
I now get this error doiung feature:install, is it related to Java11?

`Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=opennms-plugins-influxdb; type=karaf.feature; version="[1.0.0.SNAPSHOT,1.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=opennms-plugins-influxdb)(type=karaf.feature)(version>=1.0.0.SNAPSHOT)(version<=1.0.0.SNAPSHOT))" [caused by: Unable to resolve opennms-plugins-influxdb/1.0.0.SNAPSHOT: missing requirement [opennms-plugins-influxdb/1.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.opennms.plugins.timeseries.influxdb-plugin; type=osgi.bundle; version="[1.0.0.SNAPSHOT,1.0.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.opennms.plugins.timeseries.influxdb-plugin/1.0.0.SNAPSHOT: missing requirement [org.opennms.plugins.timeseries.influxdb-plugin/1.0.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.karaf.shell.api.action)(version>=4.3.0)(!(version>=5.0.0)))"]]
`

**Comment by indigo423** [comment]
> Regarding Java11 I tried to do a "standard" install. I downloaded debian stable, added opennms repo and I do "apt install..."
> I let apt-get choose the java version.

yeah there is a difference in running OpenNMS and compiling OpenNMS. Right now the core components for OpenNMS need to be compiled with Java 1.8 but can run on 11. I'm not sure if we have side effects if you compile with Java 11 and bumping Karaf to 4.3.0.

**Comment by indigo423** [comment]
What I did to get it running, was compiling it with Java 1.8 and dropped the KAR file in the /opt/opennms/deploy folder. I run OpenNMS with OpenJDK 11 and that was not a problem.

**Comment by mgiammarco** [comment]
I have tried to recompile using Java8 but without luck.
I tried dropping the KAR file in deploy folder and now I see that it unzips it in data folder (but the documentation says to use repo-install)
But now what I do? I tried with opennms-influxdb:init but it does not recognize the command so I suppose it is not installed correctly. Or am I wrong?

**Comment by indigo423** [comment]
> I have tried to recompile using Java8 but without luck.
> I tried dropping the KAR file in deploy folder and now I see that it unzips it in data folder (but the documentation says to use repo-install)
> But now what I do? I tried with opennms-influxdb:init but it does not recognize the command so I suppose it is not installed correctly. Or am I wrong?

Have changed back the Karaf dependency to 4.1.5 as it where before?

**Comment by mgiammarco** [comment]
You are right, with 4.1.5 it works.
